### ISSUE TITLE
Insulate beneath stairwell

### ISSUE THREAD

**Issue by glymur** [glymur/studio#2]
Use OC R-19 to insulate the stairwell. This should provide some isolation from the furnace room.

## TODO

- [ ] Figure out measurements for coverage
- [ ] Buy insulation
- [ ] Buy lawn fabric
- [ ] Put insulation up and cover with fabric
